"""initialize sensor_measurement table

Revision ID: 56dbb826d186
Revises:
Create Date: 2025-05-17 13:35:05.350847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56dbb826d186"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_measurement",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("sensor_uuid", sa.UUID(), nullable=False),
        sa.Column("sensor_value", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_measurement_timestamp"),
        "sensor_measurement",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sensor_measurement_timestamp"), table_name="sensor_measurement"
    )
    op.drop_table("sensor_measurement")
    # ### end Alembic commands ###
