"""add unique constraint to sensor_measurement table

Revision ID: d54dd842aaf1
Revises: da56513f0563
Create Date: 2025-05-17 23:17:19.788228

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d54dd842aaf1"
down_revision: Union[str, None] = "da56513f0563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_sensor_timestamp", "sensor_measurement", ["sensor_uuid", "timestamp"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_sensor_timestamp", "sensor_measurement", type_="unique")
    # ### end Alembic commands ###
