"""initialize sensor_info table

Revision ID: e04fa31c612e
Revises:
Create Date: 2025-05-17 13:33:54.761006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e04fa31c612e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_info",
        sa.Column("sensor_uuid", sa.UUID(), nullable=False),
        sa.Column("sensor_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("sensor_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_info")
    # ### end Alembic commands ###
